import { useState } from "react";
import Sidebar from "../components/dashboard/Sidebar";
import Navbar from "../components/dashboard/Navbar";

export default function RoadmapGenerator() {
  const [projectGoal, setProjectGoal] = useState("");
  const [timeline, setTimeline] = useState("3 Months");
  const [priority, setPriority] = useState("Medium");

  return (
    <div className="min-h-screen flex bg-slate-950">
      <Sidebar />

      <div className="flex-1 min-w-0 overflow-auto">
        <Navbar />

       <main className="space-y-8 p-4 sm:p-6 lg:p-8">
          {/* Header */}
          <div className="rounded-2xl border border-slate-800 bg-slate-900 p-8">
            <h1 className="text-3xl font-bold text-white">
              AI Roadmap Generator
            </h1>

            <p className="mt-3 text-slate-400">
              Generate intelligent product roadmaps based on project goals and
              customer feedback.
            </p>
          </div>

          {/* Roadmap Form */}
          <div className="rounded-2xl border border-slate-800 bg-slate-900 p-8">
            <h2 className="mb-6 text-xl font-semibold text-white">
              Roadmap Details
            </h2>

            <div className="space-y-6">
              <div>
                <label className="mb-2 block text-sm font-medium text-slate-300">
                  Product Goal
                </label>

                <textarea
                  rows={5}
                  value={projectGoal}
                  onChange={(e) => setProjectGoal(e.target.value)}
                  placeholder="Describe your product vision and objectives..."
                  className="w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3 text-white placeholder-slate-500 focus:border-cyan-500 focus:outline-none"
                />
              </div>

              <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
                <div>
                  <label className="mb-2 block text-sm font-medium text-slate-300">
                    Timeline
                  </label>

                  <select
                    value={timeline}
                    onChange={(e) => setTimeline(e.target.value)}
                    className="w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3 text-white focus:border-cyan-500 focus:outline-none"
                  >
                    <option>1 Month</option>
                    <option>3 Months</option>
                    <option>6 Months</option>
                    <option>12 Months</option>
                  </select>
                </div>

                <div>
                  <label className="mb-2 block text-sm font-medium text-slate-300">
                    Priority
                  </label>

                  <select
                    value={priority}
                    onChange={(e) => setPriority(e.target.value)}
                    className="w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3 text-white focus:border-cyan-500 focus:outline-none"
                  >
                    <option>Low</option>
                    <option>Medium</option>
                    <option>High</option>
                  </select>
                </div>
              </div>

              <button className="w-full rounded-xl bg-cyan-500 py-3 font-semibold text-white transition hover:bg-cyan-600">
                Generate AI Roadmap
              </button>
            </div>
          </div>

          {/* AI Generated Roadmap */}
          <div className="rounded-2xl border border-slate-800 bg-slate-900 p-8">
            <h2 className="text-xl font-semibold text-white">
              AI Generated Roadmap
            </h2>

            <p className="mt-2 text-slate-400">
              Example roadmap generated by the AI assistant.
            </p>

            <div className="mt-8 space-y-6">
              <div className="rounded-xl border border-cyan-500/20 bg-cyan-500/10 p-6">
                <h3 className="text-lg font-semibold text-cyan-400">
                  📌 Phase 1 — Research & Discovery
                </h3>

                <ul className="mt-4 list-disc space-y-2 pl-6 text-slate-300">
                  <li>Analyze customer feedback</li>
                  <li>Identify pain points</li>
                  <li>Prioritize product requirements</li>
                </ul>
              </div>

              <div className="rounded-xl border border-yellow-500/20 bg-yellow-500/10 p-6">
                <h3 className="text-lg font-semibold text-yellow-400">
                  🚀 Phase 2 — MVP Development
                </h3>

                <ul className="mt-4 list-disc space-y-2 pl-6 text-slate-300">
                  <li>Build core features</li>
                  <li>Implement authentication</li>
                  <li>Develop AI feedback analysis</li>
                </ul>
              </div>

              <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-6">
                <h3 className="text-lg font-semibold text-emerald-400">
                  📈 Phase 3 — Launch & Optimization
                </h3>

                <ul className="mt-4 list-disc space-y-2 pl-6 text-slate-300">
                  <li>Deploy production version</li>
                  <li>Monitor user feedback</li>
                  <li>Continuously improve AI suggestions</li>
                </ul>
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}